name: domestic_finance_analytics

services: 
  db:   
    profiles: ["all", "db"]
    build: 
      context: .
      dockerfile: ./devops/services/postgres/postgres.Dockerfile
    container_name: dfa-pgdb
    volumes:  
      - ./data/db:/var/lib/postgresql/data
    env_file: 
      - ./devops/services/postgres/.env
    ports:
      - "5432:5432"