name: domestic_finance_analytics

services: 
  db:   
    profiles: ["all", "db"]
    build: 
      context: .
      dockerfile: ./devops/services/postgres/postgres.Dockerfile
    container_name: dfa-pgdb
    volumes:  
      - ./data/db:/var/lib/postgresql/data
    env_file: 
      - .env
    ports:
      - "5432:5432"

  django: 
    profiles: ["all", "django"]
    build: 
      context: .
      dockerfile: ./devops/services/django/django.Dockerfile
    container_name: dfa-django
    volumes: 
      - .:/app
    env_file: 
      - .env
    ports: 
      - "8000:8000"
    depends_on: 
      - db