# Generated by Django 5.0 on 2024-07-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('long_name', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='Unknown', max_length=100)),
                ('content', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(blank=True, default=True)),
                ('in_promo', models.BooleanField(blank=True, default=False, null=True)),
                ('nutriscore', models.CharField(blank=True, max_length=1, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('is_bio', models.BooleanField(blank=True, null=True)),
                ('is_new', models.BooleanField(blank=True, null=True)),
                ('in_season', models.BooleanField(blank=True, null=True)),
                ('season_start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groceries.article')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='groceries.shop')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'ordering': ['id'],
            },
        ),
    ]
