# Generated by Django 5.0 on 2024-07-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
